import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";
import Header from "@/components/Header";
import { Red_Hat_Display } from "next/font/google";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatDisplay.className} text-base overflow-x-hidden `}
      >
        {children}
      </body>
    </html>
  );
}
